kind: pipeline
type: docker
name: e2etest

steps:
  - name: waveentry-server
    image: owncloudci/nodejs:14
    detach: true
    environment:
      DB_HOST: mongodb
      SERVER_PORT: 3001
      JWT_SECRET: abcd1234
      DB_PORT: 27017
      DB_NAME: waveentrydatabase
    commands:
      - git clone https://github.com/SagarGi/wave-entry-server.git /waveentry-server
      - cd /waveentry-server
      - npm ci
      - npm start
  
  - name: waveentry
    image: owncloudci/nodejs:14
    detach: true
    environment:
      REACT_APP_SERVER_URI: http://waveentry-server:3001
    commands:
      - npm ci
      - BROWSER=none npm start

  - name: wait
    image: owncloudci/wait-for:latest
    commands:
      - wait-for -it waveentry-server:3001 -t 300
      - wait-for -it waveentry:3000 -t 300

  - name: acceptance-test
    image: owncloudci/nodejs:14
    environment:
      SERVER_URL: http://waveentry-server:3001
      WEB_URL: http://waveentry:3000
    commands:
      - npm run test:e2e tests/acceptance/features/login.feature

services:
  - name: mongodb
    image: mongo

trigger:
  branch:
    - master
