services:
  mongodb:
    image: mongo
    container_name: mongodb

  waveentry-server:
    image: waveentry-server
    container_name: waveentry-server
    environment:
      - DB_HOST=mongodb
      - SERVER_PORT=3001
      - JWT_SECRET=abcd1234
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  # seeder:
  #   image: waveentry-server
  #   command: "npm run db:seed"
  #   depends_on:
  #     - mongodb
  #     - waveentry-server

  waveentry-web:
    image: waveentry
    container_name: waveentry-web
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - waveentry-server
      # - seeder

